# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Biblia.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(697, 696)
        Form.setStyleSheet("background-color: rgb(21, 255, 216);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.livro_edit = QtWidgets.QLineEdit(Form)
        self.livro_edit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.livro_edit.setStyleSheet("border: 2px solid rgb(0, 0, 0);\n"
"border-radius: 3px;\n"
"color: rgb(0, 0, 0);")
        self.livro_edit.setObjectName("livro_edit")
        self.verticalLayout.addWidget(self.livro_edit)
        self.capitulo_edit = QtWidgets.QLineEdit(Form)
        self.capitulo_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.capitulo_edit.setStyleSheet("border: 2px solid rgb(0, 0, 0);\n"
"border-radius: 3px;\n"
"color: rgb(0, 0, 0);")
        self.capitulo_edit.setObjectName("capitulo_edit")
        self.verticalLayout.addWidget(self.capitulo_edit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pesquisa_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pesquisa_button.sizePolicy().hasHeightForWidth())
        self.pesquisa_button.setSizePolicy(sizePolicy)
        self.pesquisa_button.setMinimumSize(QtCore.QSize(60, 40))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pesquisa_button.setFont(font)
        self.pesquisa_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:Hover {\n"
"    background-color: rgb(186, 251, 252);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(80, 153, 145);\n"
"}")
        self.pesquisa_button.setObjectName("pesquisa_button")
        self.horizontalLayout_3.addWidget(self.pesquisa_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.versiculo_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.versiculo_label.setFont(font)
        self.versiculo_label.setStyleSheet("color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(0, 0, 0);\n"
"border-radius: 3px")
        self.versiculo_label.setObjectName("versiculo_label")
        self.verticalLayout_3.addWidget(self.versiculo_label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Livro</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Capítulo</span></p></body></html>"))
        self.pesquisa_button.setText(_translate("Form", "Pesquisar"))
        self.versiculo_label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Nada Pesquisado</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
